#############################################################################
# Makefile for building: jeu
# Generated by qmake (3.1) (Qt 5.12.8)
# Project:  Projet_lo21.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Projet_lo21.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Isrc -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild/moc -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = jeu1.0.0
DISTDIR = /mnt/c/Users/alpha/Documents/Projet_lo21/build/obj/jeu1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so /usr/lib/x86_64-linux-gnu/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/Jeu.cpp \
		src/Extensions.cpp \
		src/InterfaceActions.cpp \
		src/InterfaceConsole.cpp \
		src/InterfaceCouleurJoueur.cpp \
		src/InterfaceEnvironnement.cpp \
		src/InterfaceJeu.cpp \
		src/InterfaceJoueur.cpp \
		src/InterfaceJoueurs.cpp \
		src/InterfacePioche.cpp \
		src/InterfacePlateau.cpp \
		src/InterfaceTuile.cpp \
		src/Joueur.cpp \
		src/Joueurs.cpp \
		src/Main.cpp \
		src/Pioche.cpp \
		src/Plateau.cpp \
		src/Tuile.cpp \
		src/Utils.cpp build/moc/moc_InterfaceAccueil.cpp \
		build/moc/moc_InterfaceActions.cpp \
		build/moc/moc_InterfaceCouleurJoueur.cpp \
		build/moc/moc_InterfaceEnvironnement.cpp \
		build/moc/moc_InterfaceJeu.cpp \
		build/moc/moc_InterfaceJoueur.cpp \
		build/moc/moc_InterfaceJoueurs.cpp \
		build/moc/moc_InterfacePersonnages.cpp \
		build/moc/moc_InterfacePioche.cpp \
		build/moc/moc_InterfacePlateau.cpp \
		build/moc/moc_InterfaceTuile.cpp
OBJECTS       = build/obj/Jeu.o \
		build/obj/Extensions.o \
		build/obj/InterfaceActions.o \
		build/obj/InterfaceConsole.o \
		build/obj/InterfaceCouleurJoueur.o \
		build/obj/InterfaceEnvironnement.o \
		build/obj/InterfaceJeu.o \
		build/obj/InterfaceJoueur.o \
		build/obj/InterfaceJoueurs.o \
		build/obj/InterfacePioche.o \
		build/obj/InterfacePlateau.o \
		build/obj/InterfaceTuile.o \
		build/obj/Joueur.o \
		build/obj/Joueurs.o \
		build/obj/Main.o \
		build/obj/Pioche.o \
		build/obj/Plateau.o \
		build/obj/Tuile.o \
		build/obj/Utils.o \
		build/obj/moc_InterfaceAccueil.o \
		build/obj/moc_InterfaceActions.o \
		build/obj/moc_InterfaceCouleurJoueur.o \
		build/obj/moc_InterfaceEnvironnement.o \
		build/obj/moc_InterfaceJeu.o \
		build/obj/moc_InterfaceJoueur.o \
		build/obj/moc_InterfaceJoueurs.o \
		build/obj/moc_InterfacePersonnages.o \
		build/obj/moc_InterfacePioche.o \
		build/obj/moc_InterfacePlateau.o \
		build/obj/moc_InterfaceTuile.o
DIST          = data/tuiles.csv \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Projet_lo21.pro src/Batiment.h \
		src/CarcassonneException.h \
		src/Chemin.h \
		src/Coordonnee.h \
		src/Environnement.h \
		src/EnvironnementFactory.h \
		src/EnvironnementVide.h \
		src/Extensions.h \
		src/GestionnaireMemoireEnvironnement.h \
		src/GestionnaireMemoireMeeple.h \
		src/GestionnairesMemoire.h \
		src/InterfaceAccueil.h \
		src/InterfaceActions.h \
		src/InterfaceConsole.h \
		src/InterfaceCouleurJoueur.h \
		src/InterfaceEnvironnement.h \
		src/InterfaceJeu.h \
		src/InterfaceJoueur.h \
		src/InterfaceJoueurs.h \
		src/InterfacePersonnages.h \
		src/InterfacePioche.h \
		src/InterfacePlateau.h \
		src/InterfaceTuile.h \
		src/InterfaceVariables.h \
		src/Jeu.h \
		src/Joueur.h \
		src/Joueurs.h \
		src/Personnages.h \
		src/Pioche.h \
		src/Plateau.h \
		src/Surface.h \
		src/Symbols.h \
		src/Tuile.h \
		src/Utils.h \
		src/const.h \
		src/types.h src/Jeu.cpp \
		src/Extensions.cpp \
		src/InterfaceActions.cpp \
		src/InterfaceConsole.cpp \
		src/InterfaceCouleurJoueur.cpp \
		src/InterfaceEnvironnement.cpp \
		src/InterfaceJeu.cpp \
		src/InterfaceJoueur.cpp \
		src/InterfaceJoueurs.cpp \
		src/InterfacePioche.cpp \
		src/InterfacePlateau.cpp \
		src/InterfaceTuile.cpp \
		src/Joueur.cpp \
		src/Joueurs.cpp \
		src/Main.cpp \
		src/Pioche.cpp \
		src/Plateau.cpp \
		src/Tuile.cpp \
		src/Utils.cpp
QMAKE_TARGET  = jeu
DESTDIR       = 
TARGET        = jeu


first: all
####### Build rules

jeu:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Projet_lo21.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Projet_lo21.pro
	$(QMAKE) -o Makefile Projet_lo21.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Projet_lo21.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Projet_lo21.pro

qmake_all: FORCE


all: Makefile jeu

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/Batiment.h src/CarcassonneException.h src/Chemin.h src/Coordonnee.h src/Environnement.h src/EnvironnementFactory.h src/EnvironnementVide.h src/Extensions.h src/GestionnaireMemoireEnvironnement.h src/GestionnaireMemoireMeeple.h src/GestionnairesMemoire.h src/InterfaceAccueil.h src/InterfaceActions.h src/InterfaceConsole.h src/InterfaceCouleurJoueur.h src/InterfaceEnvironnement.h src/InterfaceJeu.h src/InterfaceJoueur.h src/InterfaceJoueurs.h src/InterfacePersonnages.h src/InterfacePioche.h src/InterfacePlateau.h src/InterfaceTuile.h src/InterfaceVariables.h src/Jeu.h src/Joueur.h src/Joueurs.h src/Personnages.h src/Pioche.h src/Plateau.h src/Surface.h src/Symbols.h src/Tuile.h src/Utils.h src/const.h src/types.h $(DISTDIR)/
	$(COPY_FILE) --parents src/Jeu.cpp src/Extensions.cpp src/InterfaceActions.cpp src/InterfaceConsole.cpp src/InterfaceCouleurJoueur.cpp src/InterfaceEnvironnement.cpp src/InterfaceJeu.cpp src/InterfaceJoueur.cpp src/InterfaceJoueurs.cpp src/InterfacePioche.cpp src/InterfacePlateau.cpp src/InterfaceTuile.cpp src/Joueur.cpp src/Joueurs.cpp src/Main.cpp src/Pioche.cpp src/Plateau.cpp src/Tuile.cpp src/Utils.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o build/moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_InterfaceAccueil.cpp build/moc/moc_InterfaceActions.cpp build/moc/moc_InterfaceCouleurJoueur.cpp build/moc/moc_InterfaceEnvironnement.cpp build/moc/moc_InterfaceJeu.cpp build/moc/moc_InterfaceJoueur.cpp build/moc/moc_InterfaceJoueurs.cpp build/moc/moc_InterfacePersonnages.cpp build/moc/moc_InterfacePioche.cpp build/moc/moc_InterfacePlateau.cpp build/moc/moc_InterfaceTuile.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_InterfaceAccueil.cpp build/moc/moc_InterfaceActions.cpp build/moc/moc_InterfaceCouleurJoueur.cpp build/moc/moc_InterfaceEnvironnement.cpp build/moc/moc_InterfaceJeu.cpp build/moc/moc_InterfaceJoueur.cpp build/moc/moc_InterfaceJoueurs.cpp build/moc/moc_InterfacePersonnages.cpp build/moc/moc_InterfacePioche.cpp build/moc/moc_InterfacePlateau.cpp build/moc/moc_InterfaceTuile.cpp
build/moc/moc_InterfaceAccueil.cpp: src/InterfaceAccueil.h \
		src/InterfaceJeu.h \
		src/Jeu.h \
		src/Coordonnee.h \
		src/Plateau.h \
		src/Extensions.h \
		src/Personnages.h \
		src/Joueur.h \
		src/Pioche.h \
		src/Tuile.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/InterfaceConsole.h \
		src/Joueurs.h \
		src/types.h \
		src/InterfacePlateau.h \
		src/InterfaceTuile.h \
		src/InterfaceEnvironnement.h \
		src/const.h \
		src/InterfaceJoueurs.h \
		src/InterfaceJoueur.h \
		src/InterfaceCouleurJoueur.h \
		src/InterfacePioche.h \
		src/InterfaceActions.h \
		src/InterfacePersonnages.h \
		src/InterfaceVariables.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfaceAccueil.h -o build/moc/moc_InterfaceAccueil.cpp

build/moc/moc_InterfaceActions.cpp: src/InterfaceActions.h \
		src/Extensions.h \
		src/InterfacePersonnages.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfaceActions.h -o build/moc/moc_InterfaceActions.cpp

build/moc/moc_InterfaceCouleurJoueur.cpp: src/InterfaceCouleurJoueur.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfaceCouleurJoueur.h -o build/moc/moc_InterfaceCouleurJoueur.cpp

build/moc/moc_InterfaceEnvironnement.cpp: src/InterfaceEnvironnement.h \
		src/Tuile.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/Personnages.h \
		src/Joueur.h \
		src/const.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfaceEnvironnement.h -o build/moc/moc_InterfaceEnvironnement.cpp

build/moc/moc_InterfaceJeu.cpp: src/InterfaceJeu.h \
		src/Jeu.h \
		src/Coordonnee.h \
		src/Plateau.h \
		src/Extensions.h \
		src/Personnages.h \
		src/Joueur.h \
		src/Pioche.h \
		src/Tuile.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/InterfaceConsole.h \
		src/Joueurs.h \
		src/types.h \
		src/InterfacePlateau.h \
		src/InterfaceTuile.h \
		src/InterfaceEnvironnement.h \
		src/const.h \
		src/InterfaceJoueurs.h \
		src/InterfaceJoueur.h \
		src/InterfaceCouleurJoueur.h \
		src/InterfacePioche.h \
		src/InterfaceActions.h \
		src/InterfacePersonnages.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfaceJeu.h -o build/moc/moc_InterfaceJeu.cpp

build/moc/moc_InterfaceJoueur.cpp: src/InterfaceJoueur.h \
		src/InterfaceCouleurJoueur.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfaceJoueur.h -o build/moc/moc_InterfaceJoueur.cpp

build/moc/moc_InterfaceJoueurs.cpp: src/InterfaceJoueurs.h \
		src/CarcassonneException.h \
		src/Joueurs.h \
		src/Joueur.h \
		src/InterfaceJoueur.h \
		src/InterfaceCouleurJoueur.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfaceJoueurs.h -o build/moc/moc_InterfaceJoueurs.cpp

build/moc/moc_InterfacePersonnages.cpp: src/InterfacePersonnages.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfacePersonnages.h -o build/moc/moc_InterfacePersonnages.cpp

build/moc/moc_InterfacePioche.cpp: src/InterfacePioche.h \
		src/Tuile.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/Personnages.h \
		src/Joueur.h \
		src/InterfaceTuile.h \
		src/InterfaceEnvironnement.h \
		src/const.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfacePioche.h -o build/moc/moc_InterfacePioche.cpp

build/moc/moc_InterfacePlateau.cpp: src/InterfacePlateau.h \
		src/Plateau.h \
		src/Extensions.h \
		src/Personnages.h \
		src/Joueur.h \
		src/Coordonnee.h \
		src/Pioche.h \
		src/Tuile.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/InterfaceTuile.h \
		src/InterfaceEnvironnement.h \
		src/const.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfacePlateau.h -o build/moc/moc_InterfacePlateau.cpp

build/moc/moc_InterfaceTuile.cpp: src/InterfaceTuile.h \
		src/Personnages.h \
		src/Joueur.h \
		src/CarcassonneException.h \
		src/InterfaceEnvironnement.h \
		src/Tuile.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/Environnement.h \
		src/const.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /mnt/c/Users/alpha/Documents/Projet_lo21/build/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21 -I/mnt/c/Users/alpha/Documents/Projet_lo21/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/InterfaceTuile.h -o build/moc/moc_InterfaceTuile.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/obj/Jeu.o: src/Jeu.cpp src/Joueurs.h \
		src/Joueur.h \
		src/GestionnairesMemoire.h \
		src/GestionnaireMemoireMeeple.h \
		src/Personnages.h \
		src/GestionnaireMemoireEnvironnement.h \
		src/Tuile.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/Surface.h \
		src/Batiment.h \
		src/Symbols.h \
		src/Chemin.h \
		src/EnvironnementVide.h \
		src/Jeu.h \
		src/Plateau.h \
		src/Pioche.h \
		src/InterfaceConsole.h \
		src/types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Jeu.o src/Jeu.cpp

build/obj/Extensions.o: src/Extensions.cpp src/Extensions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Extensions.o src/Extensions.cpp

build/obj/InterfaceActions.o: src/InterfaceActions.cpp src/InterfaceActions.h \
		src/Extensions.h \
		src/InterfacePersonnages.h \
		src/CarcassonneException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfaceActions.o src/InterfaceActions.cpp

build/obj/InterfaceConsole.o: src/InterfaceConsole.cpp src/InterfaceConsole.h \
		src/Coordonnee.h \
		src/Joueurs.h \
		src/Joueur.h \
		src/Plateau.h \
		src/Extensions.h \
		src/Personnages.h \
		src/Pioche.h \
		src/Tuile.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfaceConsole.o src/InterfaceConsole.cpp

build/obj/InterfaceCouleurJoueur.o: src/InterfaceCouleurJoueur.cpp src/InterfaceCouleurJoueur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfaceCouleurJoueur.o src/InterfaceCouleurJoueur.cpp

build/obj/InterfaceEnvironnement.o: src/InterfaceEnvironnement.cpp src/InterfaceEnvironnement.h \
		src/Tuile.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/Personnages.h \
		src/Joueur.h \
		src/const.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfaceEnvironnement.o src/InterfaceEnvironnement.cpp

build/obj/InterfaceJeu.o: src/InterfaceJeu.cpp src/InterfaceJeu.h \
		src/Jeu.h \
		src/Coordonnee.h \
		src/Plateau.h \
		src/Extensions.h \
		src/Personnages.h \
		src/Joueur.h \
		src/Pioche.h \
		src/Tuile.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/InterfaceConsole.h \
		src/Joueurs.h \
		src/types.h \
		src/InterfacePlateau.h \
		src/InterfaceTuile.h \
		src/InterfaceEnvironnement.h \
		src/const.h \
		src/InterfaceJoueurs.h \
		src/InterfaceJoueur.h \
		src/InterfaceCouleurJoueur.h \
		src/InterfacePioche.h \
		src/InterfaceActions.h \
		src/InterfacePersonnages.h \
		src/InterfaceVariables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfaceJeu.o src/InterfaceJeu.cpp

build/obj/InterfaceJoueur.o: src/InterfaceJoueur.cpp src/InterfaceCouleurJoueur.h \
		src/InterfaceJoueur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfaceJoueur.o src/InterfaceJoueur.cpp

build/obj/InterfaceJoueurs.o: src/InterfaceJoueurs.cpp src/InterfaceJoueurs.h \
		src/CarcassonneException.h \
		src/Joueurs.h \
		src/Joueur.h \
		src/InterfaceJoueur.h \
		src/InterfaceCouleurJoueur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfaceJoueurs.o src/InterfaceJoueurs.cpp

build/obj/InterfacePioche.o: src/InterfacePioche.cpp src/InterfacePioche.h \
		src/Tuile.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/Personnages.h \
		src/Joueur.h \
		src/InterfaceTuile.h \
		src/InterfaceEnvironnement.h \
		src/const.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfacePioche.o src/InterfacePioche.cpp

build/obj/InterfacePlateau.o: src/InterfacePlateau.cpp src/Extensions.h \
		src/InterfacePlateau.h \
		src/Plateau.h \
		src/Personnages.h \
		src/Joueur.h \
		src/Coordonnee.h \
		src/Pioche.h \
		src/Tuile.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/InterfaceTuile.h \
		src/InterfaceEnvironnement.h \
		src/const.h \
		src/Surface.h \
		src/Batiment.h \
		src/Symbols.h \
		src/GestionnaireMemoireEnvironnement.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfacePlateau.o src/InterfacePlateau.cpp

build/obj/InterfaceTuile.o: src/InterfaceTuile.cpp src/Environnement.h \
		src/Personnages.h \
		src/Joueur.h \
		src/CarcassonneException.h \
		src/InterfaceTuile.h \
		src/InterfaceEnvironnement.h \
		src/Tuile.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/const.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/InterfaceTuile.o src/InterfaceTuile.cpp

build/obj/Joueur.o: src/Joueur.cpp src/Joueur.h \
		src/CarcassonneException.h \
		src/GestionnairesMemoire.h \
		src/GestionnaireMemoireMeeple.h \
		src/Personnages.h \
		src/GestionnaireMemoireEnvironnement.h \
		src/Tuile.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/Environnement.h \
		src/Surface.h \
		src/Batiment.h \
		src/Symbols.h \
		src/Chemin.h \
		src/EnvironnementVide.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Joueur.o src/Joueur.cpp

build/obj/Joueurs.o: src/Joueurs.cpp src/Joueurs.h \
		src/Joueur.h \
		src/CarcassonneException.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Joueurs.o src/Joueurs.cpp

build/obj/Main.o: src/Main.cpp src/Jeu.h \
		src/Coordonnee.h \
		src/Plateau.h \
		src/Extensions.h \
		src/Personnages.h \
		src/Joueur.h \
		src/Pioche.h \
		src/Tuile.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/InterfaceConsole.h \
		src/Joueurs.h \
		src/types.h \
		src/InterfaceJeu.h \
		src/InterfacePlateau.h \
		src/InterfaceTuile.h \
		src/InterfaceEnvironnement.h \
		src/const.h \
		src/InterfaceJoueurs.h \
		src/InterfaceJoueur.h \
		src/InterfaceCouleurJoueur.h \
		src/InterfacePioche.h \
		src/InterfaceActions.h \
		src/InterfacePersonnages.h \
		src/GestionnairesMemoire.h \
		src/GestionnaireMemoireMeeple.h \
		src/GestionnaireMemoireEnvironnement.h \
		src/Surface.h \
		src/Batiment.h \
		src/Symbols.h \
		src/Chemin.h \
		src/EnvironnementVide.h \
		src/InterfaceAccueil.h \
		src/InterfaceVariables.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Main.o src/Main.cpp

build/obj/Pioche.o: src/Pioche.cpp src/Utils.h \
		src/CarcassonneException.h \
		src/Pioche.h \
		src/Extensions.h \
		src/Tuile.h \
		src/Coordonnee.h \
		src/Environnement.h \
		src/Personnages.h \
		src/Joueur.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Pioche.o src/Pioche.cpp

build/obj/Plateau.o: src/Plateau.cpp src/Environnement.h \
		src/Personnages.h \
		src/Joueur.h \
		src/CarcassonneException.h \
		src/Plateau.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/Pioche.h \
		src/Tuile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Plateau.o src/Plateau.cpp

build/obj/Tuile.o: src/Tuile.cpp src/Tuile.h \
		src/Extensions.h \
		src/Coordonnee.h \
		src/CarcassonneException.h \
		src/Environnement.h \
		src/Personnages.h \
		src/Joueur.h \
		src/EnvironnementFactory.h \
		src/Symbols.h \
		src/GestionnairesMemoire.h \
		src/GestionnaireMemoireMeeple.h \
		src/GestionnaireMemoireEnvironnement.h \
		src/Surface.h \
		src/Batiment.h \
		src/Chemin.h \
		src/EnvironnementVide.h \
		src/Utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Tuile.o src/Tuile.cpp

build/obj/Utils.o: src/Utils.cpp src/Utils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/Utils.o src/Utils.cpp

build/obj/moc_InterfaceAccueil.o: build/moc/moc_InterfaceAccueil.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfaceAccueil.o build/moc/moc_InterfaceAccueil.cpp

build/obj/moc_InterfaceActions.o: build/moc/moc_InterfaceActions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfaceActions.o build/moc/moc_InterfaceActions.cpp

build/obj/moc_InterfaceCouleurJoueur.o: build/moc/moc_InterfaceCouleurJoueur.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfaceCouleurJoueur.o build/moc/moc_InterfaceCouleurJoueur.cpp

build/obj/moc_InterfaceEnvironnement.o: build/moc/moc_InterfaceEnvironnement.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfaceEnvironnement.o build/moc/moc_InterfaceEnvironnement.cpp

build/obj/moc_InterfaceJeu.o: build/moc/moc_InterfaceJeu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfaceJeu.o build/moc/moc_InterfaceJeu.cpp

build/obj/moc_InterfaceJoueur.o: build/moc/moc_InterfaceJoueur.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfaceJoueur.o build/moc/moc_InterfaceJoueur.cpp

build/obj/moc_InterfaceJoueurs.o: build/moc/moc_InterfaceJoueurs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfaceJoueurs.o build/moc/moc_InterfaceJoueurs.cpp

build/obj/moc_InterfacePersonnages.o: build/moc/moc_InterfacePersonnages.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfacePersonnages.o build/moc/moc_InterfacePersonnages.cpp

build/obj/moc_InterfacePioche.o: build/moc/moc_InterfacePioche.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfacePioche.o build/moc/moc_InterfacePioche.cpp

build/obj/moc_InterfacePlateau.o: build/moc/moc_InterfacePlateau.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfacePlateau.o build/moc/moc_InterfacePlateau.cpp

build/obj/moc_InterfaceTuile.o: build/moc/moc_InterfaceTuile.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_InterfaceTuile.o build/moc/moc_InterfaceTuile.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

